### ISSUE TITLE
Inline MathML expressions should not use display="block"

### ISSUE THREAD

**Issue by fred-wang** [rniwa/tex-to-mathml-svg#1]
Inline MathML expressions use display="block" which seems to cause bad vertical alignment on WebKit for tall expression due to the nested inline-block spans. They should instead use the default value display="inline".

See for example https://rniwa.com/2018-06-26/roth-vs-traditional/#use-mathml

**Comment by rniwa** [comment]
Well, given Firefox can handle this just fine, this should really be fixed in WebKit instead.

**Comment by fred-wang** [comment]
@rniwa Note that in general the MathML display attribute specify the inline/display mode of math formulaes (in the TeX sense) so it is wrong to use "block" for inline expressions. That might lead to spacing and other layout differences.
